### ISSUE TITLE
Port to QGIS 3

### ISSUE THREAD

**Issue by PedroVenancio** [BrunoCombal/PointToPolygon#6]
Dear Bruno,

Do you plan to port this fantastic plugin to QGIS 3?

Thank you very much!

**Comment by ksufinger** [comment]
@PedroVenancio: I was also looking for this feature.  You should be able to perform the same function as this tool from the QGIS processing toolbox using 'Rectangles, ovals, diamonds (fixed)' under the vector geometry category.

**Comment by PedroVenancio** [comment]
Hi @ksufinger 

Thank you very much for pointing me to 'Rectangles, ovals, diamonds (fixed)'! It really does the job!

Thanks!

**Comment by BrunoCombal** [comment]
Hello Pedro,

Thanks for the kind word. Unfortunately, I do not have time anymore for porting to Qgis3. 
Happy to see that Qgis has a similar tool now (i wrote it because I was missing it). 

Bruno

**Comment by PedroVenancio** [comment]
Thank you very much @BrunoCombal !
